#!/usr/bin/python
from sys import argv
from torus import Torus
from bisection import bisection
from newton import newton
from secant import secant
from error_handling import check_errors

def display_help():
    print("""USAGE
    ./105torus opt a0 a1 a2 a3 a4 n

DESCRIPTION
    opt\t\tmethod option:
    \t\t\t1 for the bisection method
    \t\t\t2 for Newton’s method
    \t\t\t3 for the secant method
    a[0-4]\tcoefficients of the equation
    n\t\tprecision (the application of the polynomial to the solution should
    \t\tbe smaller than 10ˆ-n)""")
    exit(0)


if __name__ == "__main__":
    if len(argv) == 2 and argv[1] == "-h":
        display_help()
    check_errors(argv)
    tor = Torus(argv[2], argv[3], argv[4], argv[5], argv[6], argv[7])

    if argv[1] == "1":
        bisection(tor, [0, 1])
    if argv[1] == "2":
        newton(tor, 0.5)
    if argv[1] == "3":
        secant(tor, [0, 1])
