##
## EPITECH PROJECT, 2022
## antman_project
## File description:
## Makefile
##

all:
	make -C giantman/
	make -C antman/

clean:
	make -C antman/ clean
	make -C giantman/ clean

fclean:
	make -C antman/ fclean
	make -C giantman/ fclean


re: fclean all
